import snapatac2 as snap
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import scanpy as sc
sc.settings.verbosity = 3
sc.logging.print_header()
from matplotlib import rcParams

%%time
data = snap.pp.import_data(
    'fragments.tsv.gz',
    chrom_sizes=snap.genome.mm10,
    sorted_by_barcode=False,
)

BC_A=['/5Phos/AGGCCAGAGCATTCGAACGTGATGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGAAACATCGGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGATGCCTAAGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGAGTGGTCAGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGACCACTGTGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGACATTGGCGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGCAGATCTGGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGCATCAAGTGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGCGCTGATCGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGACAAGCTAGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGCTGTAGCCGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGAGTACAAGGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGAACAACCAGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGAACCGAGAGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGAACGCTTAGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGAAGACGGAGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGAAGGTACAGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGACACAGAAGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGACAGCAGAGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGACCTCCAAGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGACGCTCGAGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGACGTATCAGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGACTATGCAGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGAGAGTCAAGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGAGATCGCAGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGAGCAGGAAGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGAGTCACTAGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGATCCTGTAGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGATTGAGGAGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGCAACCACAGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGGACTAGTAGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGCAATGGAAGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGCACTTCGAGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGCAGCGTTAGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGCATACCAAGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGCCAGTTCAGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGCCGAAGTAGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGCCGTGAGAGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGCCTCCTGAGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGCGAACTTAGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGCGACTGGAGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGCGCATACAGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGCTCAATGAGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGCTGAGCCAGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGCTGGCATAGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGGAATCTGAGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGCAAGACTAGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGGAGCTGAAGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGGATAGACAGTGGCCGATGTTTCG',
'/5Phos/AGGCCAGAGCATTCGGCCACATAGTGGCCGATGTTTCG']

BC_B=['CAAGCGTTGGCTTCTCGCATCTAACGTGATATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTAAACATCGATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTATGCCTAAATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTAGTGGTCAATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTACCACTGTATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTACATTGGCATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTCAGATCTGATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTCATCAAGTATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTCGCTGATCATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTACAAGCTAATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTCTGTAGCCATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTAGTACAAGATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTAACAACCAATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTAACCGAGAATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTAACGCTTAATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTAAGACGGAATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTAAGGTACAATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTACACAGAAATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTACAGCAGAATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTACCTCCAAATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTACGCTCGAATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTACGTATCAATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTACTATGCAATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTAGAGTCAAATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTAGATCGCAATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTAGCAGGAAATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTAGTCACTAATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTATCCTGTAATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTATTGAGGAATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTCAACCACAATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTGACTAGTAATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTCAATGGAAATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTCACTTCGAATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTCAGCGTTAATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTCATACCAAATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTCCAGTTCAATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTCCGAAGTAATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTCCGTGAGAATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTCCTCCTGAATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTCGAACTTAATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTCGACTGGAATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTCGCATACAATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTCTCAATGAATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTCTGAGCCAATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTCTGGCATAATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTGAATCTGAATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTCAAGACTAATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTGAGCTGAAATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTGATAGACAATCCACGTGCTTGAG',
'CAAGCGTTGGCTTCTCGCATCTGCCACATAATCCACGTGCTTGAG']

A8bp=[]
for i in BC_A:
    i=i.split('/5Phos/')[1]
    A8bp.append(i[15:23])

B8bp=[]
for i in BC_B:
    B8bp.append(i[22:30])

barcode_locs={}
for i in range(50):
    for j in range(50):
        barcode_locs[str(B8bp[i]+A8bp[j]+'-1')]=str(i+1)+'x'+str(j+1)
coord=[]
for i in data.obs.index:
    coord.append(barcode_locs[i])
data.obs['coord']=coord
x_coord=[]
y_coord=[]
for i in data.obs['coord']:
    i=i.split('x')
    x_coord.append(i[0])
    y_coord.append(i[1])

data.obs['x_coord']=x_coord
data.obs['y_coord']=y_coord

positionfile=open('position.txt','r')
position=list(positionfile.readlines()[0].split(','))
position.remove('')

data=data[data.obs["coord"].isin(position)]